species:
  no:
    - field: "MACCITY_NO"
      operation: "add"

aces_data:
  streams:
    - name: "MACCITY_NO"
      file: "/work/data/MACCity_anthro_NOx_2000-2010_16080_time.nc"
      yearFirst: 2000
      yearLast: 2010
      yearAlign: 2020
      variables:
        - file: "MACCity"
          model: "MACCITY_NO"

diagnostics:
  output_interval_seconds: 3600
  variables: ["no"]

output:
  directory: ./aces_output
  filename_pattern: "aces_{YYYY}{MM}{DD}_{HH}{mm}{ss}.nc"
  frequency_steps: 1
  fields:
    - no