
species:
  CO:
    - operation: add
      field: CO_anthro
      hierarchy: 0
      scale: 1.0
  NOx:
    - operation: add
      field: NOx_anthro
      hierarchy: 0
      scale: 1.0

meteorology:
  temperature: air_temperature

physics_schemes: []

diagnostics:
  output_interval_seconds: 3600
  variables: []

cdeps_inline_config:
  streams: []
