title: "NOx Only Test"

grid_settings:
  nx: 360
  ny: 720
  nz: 10

domain:
  stagger: CENTER

streams_path: "test_nox_only.yaml"

emission_species:
  - name: "no"
    data:
      - name: "nox_stream"
        field: "MACCity"
        level: 1
        horizontal_regrid_method: "bilinear"
        vertical_method: "single"
        vertical_index: 1

time_settings:
  start_year: 2020
  start_month: 1
  start_day: 1
  end_year: 2020
  end_month: 1
  end_day: 2
  dt_hours: 1