meteorology:
  hourly_scalfact: HOURLY_SCALFACT

species:
  co:
    - field: "MACCITY"
      operation: "add"
      scale: 1.0
      scale_fields: ["hourly_scalfact"]

cdeps_inline_config:
  streams:
    - name: "MACCITY"
      file: "data/MACCity_4x5.nc"
    - name: "HOURLY_SCALFACT"
      file: "data/hourly.nc"
