species:
  co:
    - field: "MACCITY_CO"
      operation: "add"

aces_data:
  streams:
    - name: "MACCITY_CO"
      file: "/work/data/MACCity_4x5.nc"
      yearFirst: 2000
      yearLast: 2010
      yearAlign: 2020
      variables:
        - file: "MACCity"
          model: "MACCITY_CO"

output:
  directory: ./aces_output
  filename_pattern: "aces_{YYYY}{MM}{DD}_{HH}{mm}{ss}.nc"
  frequency_steps: 1
  fields:
    - co

diagnostics:
  output_interval_seconds: 3600
  variables: ["co"]