# ACES equivalent of HEMCO Example 5
met_mapping:
  so2_to_so4: SO2toSO4

species:
  co:
    - field: "MACCITY_CO"
      operation: "add"
  no:
    - field: "MACCITY_NO"
      operation: "add"
  so2:
    - field: "MACCITY_SO2"
      operation: "add"
  so4:
    - field: "MACCITY_SO2" # Mimic deriving SO4 from SO2
      operation: "add"
      scale_fields: ["so2_to_so4"]

cdeps_config:
  streams:
    - name: "MACCITY_CO"
      file_path: "data/MACCity.nc"
    - name: "MACCITY_NO"
      file_path: "data/MACCity.nc"
    - name: "MACCITY_SO2"
      file_path: "data/MACCity.nc"
    - name: "SO2toSO4"
      # In ACES, this can be a constant stream or a scale factor
      file_path: "data/constants.nc"
