scale_factors:
  hourly_scalfact: HOURLY_SCALFACT

masks:
  mask_europe: MASK_EUROPE

species:
  co:
    - field: "MACCITY_CO"
      category: "anthropogenic"
      hierarchy: 1
      operation: "add"
      scale_fields: ["hourly_scalfact"]
    - field: "EMEP_CO"
      category: "anthropogenic"
      hierarchy: 2
      operation: "replace"
      mask: "mask_europe"
      scale_fields: ["hourly_scalfact"]

cdeps_inline_config:
  streams:
    - name: "MACCITY_CO"
      file: "data/MACCity_4x5.nc"
    - name: "EMEP_CO"
      file: "data/EMEP_2000.nc"
    - name: "HOURLY_SCALFACT"
      file: "data/hourly.nc"
    - name: "MASK_EUROPE"
      file: "data/Canada_mask.gen.1x1.nc"
