species:
  no:
    - field: "EDGAR_NO_POW"
      category: "anthropogenic"
      operation: "add"
    - field: "CEDS_NO_AGR"
      category: "anthropogenic"
      operation: "add"

aces_data:
  streams:
    - name: "EDGAR_NO_POW"
      file: "/work/data/EDGAR_v43.NOx.POW.nc"
    - name: "CEDS_NO_AGR"
      file: "/work/data/ALK4_butanes-em-total-anthro_CEDS_1970.nc"
