species:
  co:
    - field: "MACCITY_CO"
      operation: "add"
  no:
    - field: "MACCITY_NO"
      operation: "add"
  so2:
    - field: "MACCITY_SO2"
      operation: "add"

aces_data:
  streams:
    - name: "MACCITY_CO"
      file: "/work/data/MACCity_4x5.nc"
      variables:
        - file: "MACCity"
          model: "MACCITY_CO"
    - name: "MACCITY_NO"
      file: "/work/data/MACCity_anthro_NOx_2000-2010_16080.nc"
      variables:
        - file: "MACCity"
          model: "MACCITY_NO"
    - name: "MACCITY_SO2"
      file: "/work/data/MACCity_anthro_SO2_2000-2010_16080.nc"
      variables:
        - file: "MACCity"
          model: "MACCITY_SO2"
