meteorology:
  mask_europe: MASK_EUROPE

species:
  co:
    - field: "MACCITY_CO"
      category: "anthropogenic"
      hierarchy: 1
      operation: "add"
    - field: "EMEP_CO"
      category: "anthropogenic"
      hierarchy: 2
      operation: "replace"
      mask: "mask_europe"

aces_data:
  streams:
    - name: "MACCITY_CO"
      file: "../data/MACCity_4x5.nc"
      yearFirst: 2000
      yearLast: 2010
      yearAlign: 2020
      variables:
        - file: "MACCity"
          model: "MACCITY_CO"
    - name: "EMEP_CO"
      file: "../data/HTAPv3_CO_0.1x0.1_2000.nc"
      yearFirst: 2000
      yearLast: 2010
      yearAlign: 2020
      variables:
        - file: "MACCity"
          model: "EMEP_CO"
    - name: "MASK_EUROPE"
      file: "../data/Canada_mask.gen.1x1.nc"
      variables:
        - file: "MASK"
          model: "MASK_EUROPE"
