// SPDX-License-Identifier: Apache-2.0
// CECE — Chemical Emissions Coupling Engine
// Copyright (c) HELM Project Contributors

#ifndef CECE_UTC_GRID_HPP
#define CECE_UTC_GRID_HPP

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace cece {

/**
 * @brief Grid constants for the cosine-reduced static UTC-offset raster
 *        (data/utc_grid_f720r.rle).
 *
 * The grid keeps 1440 uniform latitude rows (0.125°, centers
 * lat = 90 - (row + 0.5) * 0.125) laid out North→South, West→East, but tapers
 * the number of columns toward the poles so each row holds
 * ncol(row) = max(4, 4 * round(720 * cos(lat_center))) points. This preserves
 * ~14 km ground resolution everywhere while dropping ~36% of the cells of the
 * old 1440x2880 regular raster — timezone-offset data does not need 0.125°
 * resolution near the poles. Generated by scripts/python/utcoffset_generator.py
 * from a timezone database snapshot.
 */
inline constexpr int kUtcGridRows = 1440;                    ///< 180° / 0.125°
inline constexpr int kUtcGridEquatorCols = 2880;             ///< 360° / 0.125° at the equator
inline constexpr int kUtcGridMinCols = 4;                    ///< Floor on tapered polar rows
inline constexpr double kUtcGridStepDeg = 0.125;             ///< Latitude cell size in degrees
inline constexpr int kUtcOffsetQuarterHoursPerSecond = 900;  ///< 15 minutes in seconds
inline constexpr std::uint32_t kUtcGridMagic = 0x31435455u;  ///< 'UTC1' read as little-endian uint32

/**
 * @brief A decoded, dense, host-resident UTC-offset grid on the reduced lattice.
 *
 * Row widths vary (cosine taper); `cells` is the concatenation of all rows in
 * North→South order, and `row_offset[r]` is the flat index of row `r`'s first
 * column, so cell (row, col) is `cells[row_offset[row] + col]`. `row_offset`
 * has `nrows + 1` entries and `row_offset[nrows] == cells.size()`.
 */
struct UtcGrid {
    int nrows = 0;                        ///< Latitude rows (== kUtcGridRows for shipped data)
    std::vector<std::uint16_t> ncol;      ///< Column count per row, size nrows
    std::vector<std::size_t> row_offset;  ///< Prefix sums, size nrows + 1
    std::vector<std::int8_t> cells;       ///< Dense quarter-hour offsets, size row_offset[nrows]

    /// @brief Flat index of cell (row, col); no bounds check (hot lookup path).
    std::size_t index(int row, int col) const {
        return row_offset[static_cast<std::size_t>(row)] + static_cast<std::size_t>(col);
    }
};

/**
 * @brief Decode a UTC-offset grid file into a dense UtcGrid (v2, self-describing).
 *
 * The file is a 4-byte magic ('UTC1'), a uint16 nrows, nrows uint16 per-row
 * column counts, then a run-length stream of little-endian 3-byte tokens
 * `(uint16_t run_length, int8_t offset_15min)`. Tokens expand row-major
 * N→S / W→E to exactly sum(ncol) cells.
 *
 * All-or-nothing: a file whose expanded length does not equal sum(ncol), whose
 * magic is wrong, or which cannot be opened/read is rejected wholesale — a
 * partially-populated grid must never mask real offsets as 0 (spec FR-003,
 * FR-008).
 *
 * @param path Path to the .rle file.
 * @return Decoded grid; every cell value is in [-128, 127] quarter-hours.
 * @throws std::runtime_error on open/read failure, bad magic, or length mismatch.
 */
UtcGrid DecodeUtcGridRle(const std::string& path);

/**
 * @brief Resolve the row index for a latitude (cell-center floor mapping).
 *
 * row = clamp(floor((90 - lat) / 0.125), 0, nrows - 1). The exact inverse of
 * the generator's cell-center rasterization (lat = 90 - (row+0.5)*0.125);
 * selects the containing (nearest) cell for any point. Unchanged by the taper.
 */
int UtcGridRowForLat(double lat);

/**
 * @brief Resolve the column index for a longitude within a row of width ncol.
 *
 * col = clamp(floor(mod(lon + 180, 360) / (360 / ncol)), 0, ncol - 1). The
 * modulo wraps 0..360 conventions; clamping covers ±180° edge inputs. The
 * per-row width is the only change from the old regular grid.
 */
int UtcGridColForLon(double lon, int row_ncol);

/**
 * @brief Map a decoded reduced grid onto the native simulation grid, band-local.
 *
 * For each native cell (i, j_global = j0 + j), performs a nearest-grid-cell
 * lookup (no interpolation, spec FR-004) and converts the int8 quarter-hour
 * offset to int32 seconds. Output is band-local to match the stacking kernel's
 * (i, j) indexing (research D2): out[i + j * nx], j in [0, ny_local).
 *
 * @param grid          Decoded reduced grid.
 * @param native_lons   1-D longitude coordinate array (size nx), degrees.
 * @param native_lats   1-D latitude coordinate array (size ny global), degrees.
 * @param nx            Native grid x extent.
 * @param j0            Global latitude index of this rank's first row.
 * @param ny_local      Number of latitude rows this rank owns.
 * @return Band-local offsets in seconds, size nx * ny_local.
 * @throws std::invalid_argument on coordinate-array size mismatch.
 */
std::vector<std::int32_t> MapToNativeOffsetsSec(const UtcGrid& grid, const std::vector<double>& native_lons, const std::vector<double>& native_lats,
                                                int nx, int j0, int ny_local);

}  // namespace cece

#endif  // CECE_UTC_GRID_HPP
