driver:
  start_time: "2014-07-01T00:00:00"
  end_time: "2014-07-01T05:00:00"
  timestep_seconds: 3600
  grid:
    nx: 72
    ny: 46
    lon_min: -180.0
    lon_max: 180.0
    lat_min: -90.0
    lat_max: 90.0

meteorology:
  hourly_scalfact: HOURLY_SCALFACT

species:
  co:
    - field: "MACCITY"
      operation: "add"
      scale: 1.0
      scale_fields: ["hourly_scalfact"]

cece_data:
  streams:
    - name: "MACCITY"
      file: "data/MACCity_4x5.nc"
      variables:
        - file: "MACCity"
          model: "MACCITY"
    - name: "HOURLY_SCALFACT"
      file: "data/hourly.nc"
