species:
  co:
    - field: "MACCITY_CO"
      category: "anthropogenic"
      hierarchy: 1
      operation: "add"

cece_data:
  streams:
    - name: "MACCITY_CO"
      file: "data/MACCity_4x5.nc"
      variables:
        - file: "MACCity"
          model: "MACCITY_CO"
    - name: "GFED_WDL"
      file: "data/GFED4_gen.025x025.199701.nc"
