species:
  co:
    - field: "MACCITY_CO"
      category: "anthropogenic"
      hierarchy: 1
      operation: "add"
    - field: "AEIC_CO"
      category: "aircraft"
      hierarchy: 1
      operation: "add"

cece_data:
  streams:
    - name: "MACCITY_CO"
      file: "data/MACCity_4x5.nc"
    - name: "AEIC_CO"
      file: "data/AEIC.nc"
